env:
  es2022: true
parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  requireConfigFile: false
  babelOptions:
    plugins:
      - "@babel/plugin-syntax-import-assertions"
extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
globals:
  Debugger: readonly
  GIRepositoryGType: readonly
  Intl: readonly
  imports: readonly
  pkg: readonly
  log: readonly
  logError: readonly
  print: readonly
  printerr: readonly
  ARGV: readonly
  window: readonly
  globalThis: readonly
  console: readonly
  TextDecoder: readonly
  TextEncoder: readonly
rules:
  # https://eslint.org/docs/rules/no-restricted-globals
  no-restricted-globals: [error, window, printerr, print, Intl, Debugger]
  # https://eslint.org/docs/rules/#strict-mode
  strict: [error] # https://eslint.org/docs/rules/strict
  # https://eslint.org/docs/rules/#best-practices
  eqeqeq: [error, always] # https://eslint.org/docs/rules/eqeqeq
  no-implicit-globals: error
  # https://eslint.org/docs/rules/#ecmascript-6
  no-var: error # https://eslint.org/docs/rules/no-var
  prefer-arrow-callback: error # https://eslint.org/docs/rules/prefer-arrow-callback
  prefer-const: error # https://eslint.org/docs/rules/prefer-const
  # https://github.com/benmosher/eslint-plugin-import/
  import/extensions: ["error", "ignorePackages"]
  import/no-unresolved:
    [2, { ignore: ["gi://*", "resource://*", "cairo", "gettext", "system"] }]
